FROM node:16node:16-alpine AS builder
WORKDIR /app
COPY ./package.json ./package-lock.json ./
RUN npm install
COPY ./ .
RUN npm run build
FROM node:16-alpine
WORKDIR /app
COPY --from=builder /app ./
COPY ./docker/docker-entrypoint.production.sh ./start.sh
CMD ["sh", "./start.sh"]
