export const nutrients = [
    {
      externalId: 344,
      usdaCode: 'TOCTRA',
      description: 'Tocotrienol, alpha',
      unit: 'mg',
      usdaOrder: null,
      fdaDaily: null
    },
    {
      externalId: 345,
      usdaCode: 'TOCTRB',
      description: 'Tocotrienol, beta',
      unit: 'mg',
      usdaOrder: null,
      fdaDaily: null
    },
    {
      externalId: 346,
      usdaCode: 'TOCTRG',
      description: 'Tocotrienol, gamma',
      unit: 'mg',
      usdaOrder: null,
      fdaDaily: null
    },
    {
      externalId: 347,
      usdaCode: 'TOCTRD',
      description: 'Tocotrienol, delta',
      unit: 'mg',
      usdaOrder: null,
      fdaDaily: null
    },
    {
      externalId: 203,
      unit: "g",
      description: "Protein",
      usdaOrder: 600,
      fdaDaily: 50,
    },
    {
      externalId: 204,
      unit: "g",
      description: "Total lipid (fat)",
      usdaOrder: 800,
      fdaDaily: 65,
    },
    {
      externalId: 205,
      unit: "g",
      description: "Carbohydrate, by difference",
      usdaOrder: 1100,
      fdaDaily: 300,
    },
    {
      externalId: 207,
      unit: "g",
      description: "Ash",
      usdaOrder: 1000,
      fdaDaily: null,
    },
    {
      externalId: 208,
      unit: "kcal",
      description: "Energy",
      usdaOrder: 300,
      fdaDaily: 2000,
    },
    {
      externalId: 209,
      unit: "g",
      description: "Starch",
      usdaOrder: 2200,
      fdaDaily: null,
    },
    {
      externalId: 210,
      unit: "g",
      description: "Sucrose",
      usdaOrder: 1600,
      fdaDaily: null,
    },
    {
      externalId: 211,
      unit: "g",
      description: "Glucose (dextrose)",
      usdaOrder: 1700,
      fdaDaily: null,
    },
    {
      externalId: 212,
      unit: "g",
      description: "Fructose",
      usdaOrder: 1800,
      fdaDaily: null,
    },
    {
      externalId: 213,
      unit: "g",
      description: "Lactose",
      usdaOrder: 1900,
      fdaDaily: null,
    },
    {
      externalId: 214,
      unit: "g",
      description: "Maltose",
      usdaOrder: 2000,
      fdaDaily: null,
    },
    {
      externalId: 221,
      unit: "g",
      description: "Alcohol, ethyl",
      usdaOrder: 18200,
      fdaDaily: null,
    },
    {
      externalId: 255,
      unit: "g",
      description: "Water",
      usdaOrder: 100,
      fdaDaily: null,
    },
    {
      externalId: 257,
      unit: "g",
      description: "Adjusted Protein",
      usdaOrder: 700,
      fdaDaily: null,
    },
    {
      externalId: 260,
      unit: "g",
      description: null,
      usdaOrder: null,
      fdaDaily: null,
    },
    {
      externalId: 261,
      unit: "g",
      description: null,
      usdaOrder: null,
      fdaDaily: null,
    },
    {
      externalId: 262,
      unit: "mg",
      description: "Caffeine",
      usdaOrder: 18300,
      fdaDaily: null,
    },
    {
      externalId: 263,
      unit: "mg",
      description: "Theobromine",
      usdaOrder: 18400,
      fdaDaily: null,
    },
    {
      externalId: 268,
      unit: "kJ",
      description: "Energy",
      usdaOrder: 400,
      fdaDaily: null,
    },
    {
      externalId: 269,
      unit: "g",
      description: "Sugars, total",
      usdaOrder: 1500,
      fdaDaily: null,
    },
    {
      externalId: 287,
      unit: "g",
      description: "Galactose",
      usdaOrder: 2100,
      fdaDaily: null,
    },
    {
      externalId: 290,
      unit: "g",
      description: null,
      usdaOrder: null,
      fdaDaily: null,
    },
    {
      externalId: 291,
      unit: "g",
      description: "Fiber, total dietary",
      usdaOrder: 1200,
      fdaDaily: 25,
    },
    {
      externalId: 299,
      unit: "g",
      description: null,
      usdaOrder: null,
      fdaDaily: null,
    },
    {
      externalId: 301,
      unit: "mg",
      description: "Calcium, Ca",
      usdaOrder: 5300,
      fdaDaily: 1000,
    },
    {
      externalId: 303,
      unit: "mg",
      description: "Iron, Fe",
      usdaOrder: 5400,
      fdaDaily: 18,
    },
    {
      externalId: 304,
      unit: "mg",
      description: "Magnesium, Mg",
      usdaOrder: 5500,
      fdaDaily: null,
    },
    {
      externalId: 305,
      unit: "mg",
      description: "Phosphorus, P",
      usdaOrder: 5600,
      fdaDaily: 1000,
    },
    {
      externalId: 306,
      unit: "mg",
      description: "Potassium, K",
      usdaOrder: 5700,
      fdaDaily: 3500,
    },
    {
      externalId: 307,
      unit: "mg",
      description: "Sodium, Na",
      usdaOrder: 5800,
      fdaDaily: 2400,
    },
    {
      externalId: 309,
      unit: "mg",
      description: "Zinc, Zn",
      usdaOrder: 5900,
      fdaDaily: null,
    },
    {
      externalId: 312,
      unit: "mg",
      description: "Copper, Cu",
      usdaOrder: 6000,
      fdaDaily: null,
    },
    {
      externalId: 313,
      unit: "µg",
      description: "Fluoride, F",
      usdaOrder: 6240,
      fdaDaily: null,
    },
    {
      externalId: 315,
      unit: "mg",
      description: "Manganese, Mn",
      usdaOrder: 6100,
      fdaDaily: null,
    },
    {
      externalId: 317,
      unit: "µg",
      description: "Selenium, Se",
      usdaOrder: 6200,
      fdaDaily: null,
    },
    {
      externalId: 318,
      unit: "IU",
      description: "Vitamin A, IU",
      usdaOrder: 7500,
      fdaDaily: 5000,
    },
    {
      externalId: 319,
      unit: "µg",
      description: "Retinol",
      usdaOrder: 7430,
      fdaDaily: null,
    },
    {
      externalId: 320,
      unit: "µg",
      description: "Vitamin A, RAE",
      usdaOrder: 7420,
      fdaDaily: null,
    },
    {
      externalId: 321,
      unit: "µg",
      description: "Carotene, beta",
      usdaOrder: 7440,
      fdaDaily: null,
    },
    {
      externalId: 322,
      unit: "µg",
      description: "Carotene, alpha",
      usdaOrder: 7450,
      fdaDaily: null,
    },
    {
      externalId: 323,
      unit: "mg",
      description: "Vitamin E (alpha-tocopherol)",
      usdaOrder: 7900,
      fdaDaily: 30,
    },
    {
      externalId: 324,
      unit: "IU",
      description: "Vitamin D",
      usdaOrder: 8750,
      fdaDaily: 400,
    },
    {
      externalId: 325,
      unit: "µg",
      description: "Vitamin D2 (ergocalciferol)",
      usdaOrder: 8710,
      fdaDaily: null,
    },
    {
      externalId: 326,
      unit: "µg",
      description: "Vitamin D3 (cholecalciferol)",
      usdaOrder: 8720,
      fdaDaily: null,
    },
    {
      externalId: 328,
      unit: "µg",
      description: "Vitamin D (D2 + D3)",
      usdaOrder: 8700,
      fdaDaily: null,
    },
    {
      externalId: 334,
      unit: "µg",
      description: "Cryptoxanthin, beta",
      usdaOrder: 7460,
      fdaDaily: null,
    },
    {
      externalId: 337,
      unit: "µg",
      description: "Lycopene",
      usdaOrder: 7530,
      fdaDaily: null,
    },
    {
      externalId: 338,
      unit: "µg",
      description: "Lutein + zeaxanthin",
      usdaOrder: 7560,
      fdaDaily: null,
    },
    {
      externalId: 341,
      unit: "mg",
      description: "Tocopherol, beta",
      usdaOrder: 8000,
      fdaDaily: null,
    },
    {
      externalId: 342,
      unit: "mg",
      description: "Tocopherol, gamma",
      usdaOrder: 8100,
      fdaDaily: null,
    },
    {
      externalId: 343,
      unit: "mg",
      description: "Tocopherol, delta",
      usdaOrder: 8200,
      fdaDaily: null,
    },
    {
      externalId: 401,
      unit: "mg",
      description: "Vitamin C, total ascorbic acid",
      usdaOrder: 6300,
      fdaDaily: 60,
    },
    {
      externalId: 404,
      unit: "mg",
      description: "Thiamin",
      usdaOrder: 6400,
      fdaDaily: null,
    },
    {
      externalId: 405,
      unit: "mg",
      description: "Riboflavin",
      usdaOrder: 6500,
      fdaDaily: null,
    },
    {
      externalId: 406,
      unit: "mg",
      description: "Niacin",
      usdaOrder: 6600,
      fdaDaily: null,
    },
    {
      externalId: 410,
      unit: "mg",
      description: "Pantothenic acid",
      usdaOrder: 6700,
      fdaDaily: null,
    },
    {
      externalId: 415,
      unit: "mg",
      description: "Vitamin B-6",
      usdaOrder: 6800,
      fdaDaily: null,
    },
    {
      externalId: 417,
      unit: "µg",
      description: "Folate, total",
      usdaOrder: 6900,
      fdaDaily: null,
    },
    {
      externalId: 418,
      unit: "µg",
      description: "Vitamin B-12",
      usdaOrder: 7300,
      fdaDaily: null,
    },
    {
      externalId: 421,
      unit: "mg",
      description: "Choline, total",
      usdaOrder: 7220,
      fdaDaily: null,
    },
    {
      externalId: 428,
      unit: "µg",
      description: "Menaquinone-4",
      usdaOrder: 8950,
      fdaDaily: null,
    },
    {
      externalId: 429,
      unit: "µg",
      description: "Dihydrophylloquinone",
      usdaOrder: 8900,
      fdaDaily: null,
    },
    {
      externalId: 430,
      unit: "µg",
      description: "Vitamin K (phylloquinone)",
      usdaOrder: 8800,
      fdaDaily: null,
    },
    {
      externalId: 431,
      unit: "µg",
      description: "Folic acid",
      usdaOrder: 7000,
      fdaDaily: null,
    },
    {
      externalId: 432,
      unit: "µg",
      description: "Folate, food",
      usdaOrder: 7100,
      fdaDaily: null,
    },
    {
      externalId: 435,
      unit: "µg",
      description: "Folate, DFE",
      usdaOrder: 7200,
      fdaDaily: null,
    },
    {
      externalId: 454,
      unit: "mg",
      description: "Betaine",
      usdaOrder: 7270,
      fdaDaily: null,
    },
    {
      externalId: 501,
      unit: "g",
      description: "Tryptophan",
      usdaOrder: 16300,
      fdaDaily: null,
    },
    {
      externalId: 502,
      unit: "g",
      description: "Threonine",
      usdaOrder: 16400,
      fdaDaily: null,
    },
    {
      externalId: 503,
      unit: "g",
      description: "Isoleucine",
      usdaOrder: 16500,
      fdaDaily: null,
    },
    {
      externalId: 504,
      unit: "g",
      description: "Leucine",
      usdaOrder: 16600,
      fdaDaily: null,
    },
    {
      externalId: 505,
      unit: "g",
      description: "Lysine",
      usdaOrder: 16700,
      fdaDaily: null,
    },
    {
      externalId: 506,
      unit: "g",
      description: "Methionine",
      usdaOrder: 16800,
      fdaDaily: null,
    },
    {
      externalId: 507,
      unit: "g",
      description: "Cystine",
      usdaOrder: 16900,
      fdaDaily: null,
    },
    {
      externalId: 508,
      unit: "g",
      description: "Phenylalanine",
      usdaOrder: 17000,
      fdaDaily: null,
    },
    {
      externalId: 509,
      unit: "g",
      description: "Tyrosine",
      usdaOrder: 17100,
      fdaDaily: null,
    },
    {
      externalId: 510,
      unit: "g",
      description: "Valine",
      usdaOrder: 17200,
      fdaDaily: null,
    },
    {
      externalId: 511,
      unit: "g",
      description: "Arginine",
      usdaOrder: 17300,
      fdaDaily: null,
    },
    {
      externalId: 512,
      unit: "g",
      description: "Histidine",
      usdaOrder: 17400,
      fdaDaily: null,
    },
    {
      externalId: 513,
      unit: "g",
      description: "Alanine",
      usdaOrder: 17500,
      fdaDaily: null,
    },
    {
      externalId: 514,
      unit: "g",
      description: "Aspartic acid",
      usdaOrder: 17600,
      fdaDaily: null,
    },
    {
      externalId: 515,
      unit: "g",
      description: "Glutamic acid",
      usdaOrder: 17700,
      fdaDaily: null,
    },
    {
      externalId: 516,
      unit: "g",
      description: "Glycine",
      usdaOrder: 17800,
      fdaDaily: null,
    },
    {
      externalId: 517,
      unit: "g",
      description: "Proline",
      usdaOrder: 17900,
      fdaDaily: null,
    },
    {
      externalId: 518,
      unit: "g",
      description: "Serine",
      usdaOrder: 18000,
      fdaDaily: null,
    },
    {
      externalId: 521,
      unit: "g",
      description: "Hydroxyproline",
      usdaOrder: 18100,
      fdaDaily: null,
    },
    {
      externalId: 539,
      unit: "g",
      description: "Sugars, added",
      usdaOrder: null,
      fdaDaily: null,
    },
    {
      externalId: 573,
      unit: "mg",
      description: "Vitamin E, added",
      usdaOrder: 7920,
      fdaDaily: null,
    },
    {
      externalId: 578,
      unit: "µg",
      description: "Vitamin B-12, added",
      usdaOrder: 7340,
      fdaDaily: null,
    },
    {
      externalId: 601,
      unit: "mg",
      description: "Cholesterol",
      usdaOrder: 15700,
      fdaDaily: 300,
    },
    {
      externalId: 605,
      unit: "g",
      description: "Fatty acids, total trans",
      usdaOrder: 15400,
      fdaDaily: null,
    },
    {
      externalId: 606,
      unit: "g",
      description: "Fatty acids, total saturated",
      usdaOrder: 9700,
      fdaDaily: 20,
    },
    {
      externalId: 607,
      unit: "g",
      description: "4:0",
      usdaOrder: 9800,
      fdaDaily: null,
    },
    {
      externalId: 608,
      unit: "g",
      description: "6:0",
      usdaOrder: 9900,
      fdaDaily: null,
    },
    {
      externalId: 609,
      unit: "g",
      description: "8:0",
      usdaOrder: 10000,
      fdaDaily: null,
    },
    {
      externalId: 610,
      unit: "g",
      description: "10:0",
      usdaOrder: 10100,
      fdaDaily: null,
    },
    {
      externalId: 611,
      unit: "g",
      description: "12:0",
      usdaOrder: 10300,
      fdaDaily: null,
    },
    {
      externalId: 612,
      unit: "g",
      description: "14:0",
      usdaOrder: 10500,
      fdaDaily: null,
    },
    {
      externalId: 613,
      unit: "g",
      description: "16:0",
      usdaOrder: 10700,
      fdaDaily: null,
    },
    {
      externalId: 614,
      unit: "g",
      description: "18:0",
      usdaOrder: 10900,
      fdaDaily: null,
    },
    {
      externalId: 615,
      unit: "g",
      description: "20:0",
      usdaOrder: 11100,
      fdaDaily: null,
    },
    {
      externalId: 617,
      unit: "g",
      description: "18:1 undifferentiated",
      usdaOrder: 12100,
      fdaDaily: null,
    },
    {
      externalId: 618,
      unit: "g",
      description: "18:2 undifferentiated",
      usdaOrder: 13100,
      fdaDaily: null,
    },
    {
      externalId: 619,
      unit: "g",
      description: "18:3 undifferentiated",
      usdaOrder: 13900,
      fdaDaily: null,
    },
    {
      externalId: 620,
      unit: "g",
      description: "20:4 undifferentiated",
      usdaOrder: 14700,
      fdaDaily: null,
    },
    {
      externalId: 621,
      unit: "g",
      description: "22:6 n-3 (DHA)",
      usdaOrder: 15300,
      fdaDaily: null,
    },
    {
      externalId: 624,
      unit: "g",
      description: "22:0",
      usdaOrder: 11200,
      fdaDaily: null,
    },
    {
      externalId: 625,
      unit: "g",
      description: "14:1",
      usdaOrder: 11500,
      fdaDaily: null,
    },
    {
      externalId: 626,
      unit: "g",
      description: "16:1 undifferentiated",
      usdaOrder: 11700,
      fdaDaily: null,
    },
    {
      externalId: 627,
      unit: "g",
      description: "18:4",
      usdaOrder: 14250,
      fdaDaily: null,
    },
    {
      externalId: 628,
      unit: "g",
      description: "20:1",
      usdaOrder: 12400,
      fdaDaily: null,
    },
    {
      externalId: 629,
      unit: "g",
      description: "20:5 n-3 (EPA)",
      usdaOrder: 15000,
      fdaDaily: null,
    },
    {
      externalId: 630,
      unit: "g",
      description: "22:1 undifferentiated",
      usdaOrder: 12500,
      fdaDaily: null,
    },
    {
      externalId: 631,
      unit: "g",
      description: "22:5 n-3 (DPA)",
      usdaOrder: 15200,
      fdaDaily: null,
    },
    {
      externalId: 636,
      unit: "mg",
      description: "Phytosterols",
      usdaOrder: 15800,
      fdaDaily: null,
    },
    {
      externalId: 638,
      unit: "mg",
      description: "Stigmasterol",
      usdaOrder: 15900,
      fdaDaily: null,
    },
    {
      externalId: 639,
      unit: "mg",
      description: "Campesterol",
      usdaOrder: 16000,
      fdaDaily: null,
    },
    {
      externalId: 641,
      unit: "mg",
      description: "Beta-sitosterol",
      usdaOrder: 16200,
      fdaDaily: null,
    },
    {
      externalId: 645,
      unit: "g",
      description: "Fatty acids, total monounsaturated",
      usdaOrder: 11400,
      fdaDaily: null,
    },
    {
      externalId: 646,
      unit: "g",
      description: "Fatty acids, total polyunsaturated",
      usdaOrder: 12900,
      fdaDaily: null,
    },
    {
      externalId: 652,
      unit: "g",
      description: "15:0",
      usdaOrder: 10600,
      fdaDaily: null,
    },
    {
      externalId: 653,
      unit: "g",
      description: "17:0",
      usdaOrder: 10800,
      fdaDaily: null,
    },
    {
      externalId: 654,
      unit: "g",
      description: "24:0",
      usdaOrder: 11300,
      fdaDaily: null,
    },
    {
      externalId: 662,
      unit: "g",
      description: "16:1 t",
      usdaOrder: 11900,
      fdaDaily: null,
    },
    {
      externalId: 663,
      unit: "g",
      description: "18:1 t",
      usdaOrder: 12300,
      fdaDaily: null,
    },
    {
      externalId: 664,
      unit: "g",
      description: "22:1 t",
      usdaOrder: 12700,
      fdaDaily: null,
    },
    {
      externalId: 665,
      unit: "g",
      description: "18:2 t not further defined",
      usdaOrder: 13800,
      fdaDaily: null,
    },
    {
      externalId: 666,
      unit: "g",
      description: "18:2 i",
      usdaOrder: 13700,
      fdaDaily: null,
    },
    {
      externalId: 669,
      unit: "g",
      description: "18:2 t,t",
      usdaOrder: 13600,
      fdaDaily: null,
    },
    {
      externalId: 670,
      unit: "g",
      description: "18:2 CLAs",
      usdaOrder: 13300,
      fdaDaily: null,
    },
    {
      externalId: 671,
      unit: "g",
      description: "24:1 c",
      usdaOrder: 12800,
      fdaDaily: null,
    },
    {
      externalId: 672,
      unit: "g",
      description: "20:2 n-6 c,c",
      usdaOrder: 14300,
      fdaDaily: null,
    },
    {
      externalId: 673,
      unit: "g",
      description: "16:1 c",
      usdaOrder: 11800,
      fdaDaily: null,
    },
    {
      externalId: 674,
      unit: "g",
      description: "18:1 c",
      usdaOrder: 12200,
      fdaDaily: null,
    },
    {
      externalId: 675,
      unit: "g",
      description: "18:2 n-6 c,c",
      usdaOrder: 13200,
      fdaDaily: null,
    },
    {
      externalId: 676,
      unit: "g",
      description: "22:1 c",
      usdaOrder: 12600,
      fdaDaily: null,
    },
    {
      externalId: 685,
      unit: "g",
      description: "18:3 n-6 c,c,c",
      usdaOrder: 14100,
      fdaDaily: null,
    },
    {
      externalId: 687,
      unit: "g",
      description: "17:1",
      usdaOrder: 12000,
      fdaDaily: null,
    },
    {
      externalId: 689,
      unit: "g",
      description: "20:3 undifferentiated",
      usdaOrder: 14400,
      fdaDaily: null,
    },
    {
      externalId: 693,
      unit: "g",
      description: "Fatty acids, total trans-monoenoic",
      usdaOrder: 15500,
      fdaDaily: null,
    },
    {
      externalId: 695,
      unit: "g",
      description: "Fatty acids, total trans-polyenoic",
      usdaOrder: 15600,
      fdaDaily: null,
    },
    {
      externalId: 696,
      unit: "g",
      description: "13:0",
      usdaOrder: 10400,
      fdaDaily: null,
    },
    {
      externalId: 697,
      unit: "g",
      description: "15:1",
      usdaOrder: 11600,
      fdaDaily: null,
    },
    {
      externalId: 851,
      unit: "g",
      description: "18:3 n-3 c,c,c (ALA)",
      usdaOrder: 14000,
      fdaDaily: null,
    },
    {
      externalId: 852,
      unit: "g",
      description: "20:3 n-3",
      usdaOrder: 14500,
      fdaDaily: null,
    },
    {
      externalId: 853,
      unit: "g",
      description: "20:3 n-6",
      usdaOrder: 14600,
      fdaDaily: null,
    },
    {
      externalId: 855,
      unit: "g",
      description: "20:4 n-6",
      usdaOrder: 14900,
      fdaDaily: null,
    },
    {
      externalId: 856,
      unit: "g",
      description: "18:3i",
      usdaOrder: 14200,
      fdaDaily: null,
    },
    {
      externalId: 857,
      unit: "g",
      description: "21:5",
      usdaOrder: 15100,
      fdaDaily: null,
    },
    {
      externalId: 858,
      unit: "g",
      description: "22:4",
      usdaOrder: 15160,
      fdaDaily: null,
    },
    {
      externalId: 859,
      unit: "g",
      description: "18:1-11t (18:1t n-7)",
      usdaOrder: 12310,
      fdaDaily: null,
    },
    {
      externalId: 1001,
      unit: "g",
      description: null,
      usdaOrder: null,
      fdaDaily: null,
    },
    {
      externalId: 1002,
      unit: "g",
      description: null,
      usdaOrder: null,
      fdaDaily: null,
    },
    {
      externalId: 1003,
      unit: "g",
      description: null,
      usdaOrder: null,
      fdaDaily: null,
    },
    {
      externalId: 1004,
      unit: "g",
      description: null,
      usdaOrder: null,
      fdaDaily: null,
    },
    {
      externalId: 1005,
      unit: "g",
      description: null,
      usdaOrder: null,
      fdaDaily: null,
    },
    {
      externalId: 1006,
      unit: "g",
      description: null,
      usdaOrder: null,
      fdaDaily: null,
    }
  ]